name: linnt-and-tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - run: make lint
      - run: make p_test
      - name: Test & publish code coverage
        uses: Mandasik/python-project-50@v0.1.0
        if: github.ref_name == 'main'
        env:
          MY_TESTS: ${{ secrets.MY_TESTS }}
        with:
          coverageCommand: make test-coverage
          debug: true
